# Generated by Django 4.2.6 on 2023-10-29 14:44
import jobs.models.miscs
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vacancy",
            options={"ordering": ["title"], "verbose_name_plural": "Vacancies"},
        ),
        migrations.RemoveField(
            model_name="possibility",
            name="vacancies",
        ),
        migrations.RemoveField(
            model_name="skill",
            name="vacancies",
        ),
        migrations.AddField(
            model_name="vacancy",
            name="possibilities",
            field=models.ManyToManyField(
                blank=True, related_name="vacancies", to="jobs.possibility"
            ),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="skills",
            field=models.ManyToManyField(
                blank=True, related_name="vacancies", to="jobs.skill"
            ),
        ),
        migrations.AlterField(
            model_name="possibility",
            name="background_color",
            field=jobs.models.miscs.ColorField(default="#000000", max_length=7),
        ),
        migrations.AlterField(
            model_name="possibility",
            name="text_color",
            field=jobs.models.miscs.ColorField(default="#000000", max_length=7),
        ),
    ]
