# Generated by Django 4.2.6 on 2023-10-29 15:06
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0002_alter_vacancy_options_remove_possibility_vacancies_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vacancy",
            name="slug",
        ),
    ]
