# Generated by Django 4.2.6 on 2023-10-29 16:34
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0003_remove_vacancy_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancy",
            name="location",
            field=models.CharField(default="Earth", max_length=255),
            preserve_default=False,
        ),
    ]
