# Generated by Django 4.2.6 on 2023-10-30 17:01
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0004_vacancy_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancy",
            name="date_work",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="skill_time",
            field=models.IntegerField(default=0),
        ),
    ]
