# Generated by Django 4.2.6 on 2023-10-30 18:51
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0005_vacancy_date_work_vacancy_skill_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vacancy",
            old_name="salary",
            new_name="salary_end",
        ),
        migrations.AddField(
            model_name="vacancy",
            name="salary_start",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
