# Generated by Django 4.2.6 on 2023-11-03 20:27
import martor.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0006_rename_salary_vacancy_salary_end_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="description",
            field=martor.models.MartorField(),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="description",
            field=martor.models.MartorField(),
        ),
    ]
