# Generated by Django 4.2.6 on 2023-11-17 21:36
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0007_alter_company_description_alter_vacancy_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vacancy",
            old_name="skill_time",
            new_name="experience_time",
        ),
        migrations.RemoveField(
            model_name="vacancy",
            name="date_work",
        ),
        migrations.AddField(
            model_name="vacancy",
            name="working_days",
            field=models.SmallIntegerField(default=124),
        ),
    ]
