# Generated by Django 4.2.6 on 2023-11-18 16:03
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0008_rename_skill_time_vacancy_experience_time_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vacancy",
            old_name="salary_end",
            new_name="salary_max",
        ),
        migrations.RenameField(
            model_name="vacancy",
            old_name="salary_start",
            new_name="salary_min",
        ),
    ]
