# Generated by Django 4.2.6 on 2023-11-22 20:54
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("jobs", "0010_alter_company_owner_alter_vacancy_published_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vacancy",
            options={"ordering": ["-published_at"], "verbose_name_plural": "Vacancies"},
        ),
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("salary", models.FloatField()),
                ("phone_number", models.CharField(max_length=20)),
                ("experience", models.TextField()),
                ("education", models.TextField()),
                ("achievements", models.TextField()),
                ("hobbies", models.TextField()),
                ("additional_info", models.TextField()),
                (
                    "author",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resume",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "skills",
                    models.ManyToManyField(
                        blank=True, related_name="resumes", to="jobs.skill"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Resumes",
                "ordering": ["title"],
            },
        ),
    ]
