# Generated by Django 4.2.6 on 2023-11-23 22:16
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0011_alter_vacancy_options_resume"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancy",
            name="responded",
            field=models.ManyToManyField(
                blank=True, related_name="vacancy", to="jobs.resume"
            ),
        ),
    ]
