# Generated by Django 4.2.6 on 2023-10-30 19:20
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
