# Generated by Django 4.2.6 on 2023-11-23 00:28
import account.models
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0007_education"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, upload_to=account.models.user_avatar_path
            ),
        ),
    ]
