# Generated by Django 4.2.6 on 2023-11-23 22:16
import account.models
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0008_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="avatars/0/avatar.webp",
                upload_to=account.models.user_avatar_path,
            ),
        ),
    ]
